(ns braids.step-defs.zombie-detection)

(def step-defs
  {"Given an orchestrator with worker-timeout set to (\\d+)" (fn [timeout] (println "Setting worker-timeout to" timeout))
   "Given a worker session \"([^\"]+)\" is active" (fn [session] (println "Mocking active session:" session))
   "And the corresponding bead \"([^\"]+)\" is (\\w+)" (fn [bead status] (println "Mocking bead" bead "status:" status))
   "When checking for zombies" (fn [] (println "Checking for zombie sessions"))
   "Then the session should be marked as zombie with reason \"([^\"]+)\"" (fn [reason] (println "Verifying zombie marked with reason:" reason))
   "Given a worker session started (\\d+) hours ago" (fn [hours] (println "Mocking session started" hours "hours ago"))
   "Then no zombies should be detected" (fn [] (println "Verifying no zombies detected"))
   "Given zombies detected with sessions \"([^\"]+)\" and \"([^\"]+)\"" (fn [s1 s2] (println "Mocking zombies:" s1 "and" s2))
   "When cleaning up zombies" (fn [] (println "Cleaning up zombie sessions"))
   "Then the sessions should be killed" (fn [] (println "Verifying sessions killed"))
   "And a cleanup log should be generated" (fn [] (println "Verifying cleanup log generated"))
   "Given zombies from project \"([^\"]+)\" and \"([^\"]+)\"" (fn [p1 p2] (println "Mocking zombies from projects:" p1 "and" p2))
   "When checking for zombies across all projects" (fn [] (println "Checking zombies across all projects"))
   "Then all zombies should be detected regardless of project" (fn [] (println "Verifying all zombies detected"))
   "Given a bead references a session that no longer exists" (fn [] (println "Mocking missing session reference"))
   "Then it should not crash and continue processing" (fn [] (println "Verifying no crash on missing session"))
   "Given zombies were successfully cleaned up" (fn [] (println "Mocking successful cleanup"))
   "When generating cleanup report" (fn [] (println "Generating cleanup report"))
   "Then the report should list killed sessions and reasons" (fn [] (println "Verifying cleanup report contents"))})